### ISSUE TITLE
Failure to build from Source and AUR

### ISSUE THREAD

**Issue by TheKarion** [paulmcauley/classik#31] opened 2022-06-07 18:04 UTC
[classikinstallerror.txt](https://github.com/paulmcauley/classik/files/8855513/classikinstallerror.txt)
I made an install log, I hope this'll help. I'm on Endeavour OS and I've tried both the AUR and building from source, both give an error. If there's any additional information you need let me know.

**Comment by paulmcauley** [comment] 2022-06-07 18:28
The log file provided doesn't give the line stating the error.

However, I'm assuming this is a duplicate of #27 which has already been fixed on the Github master and will be in the next 4.0 release.

Where did you get the source code to compile, and for what release/branch? The code on the AUR is out of date and not maintained by me. Please try the source code from Github master.

**Comment by TheKarion** [comment] 2022-06-08 00:11
I got it from the master code. I was able to use a previous release which works just fine.

**Comment by journalehsan** [comment] 2022-06-11 13:06
Hi, I have same problem. In AUR. 
Erorr =
`home/ehsant/.cache/yay/classik/src/classik-3.0.breeze5.23.80/kdecoration/breezedecoration.cpp: In member function ‘void Breeze::Decoration::updateBlur()’:
/home/ehsant/.cache/yay/classik/src/classik-3.0.breeze5.23.80/kdecoration/breezedecoration.cpp:1355:13: error: ‘setBlurRegion’ was not declared in this scope
 1355 |             setBlurRegion( QRegion() );
      |             ^~~~~~~~~~~~~
/home/ehsant/.cache/yay/classik/src/classik-3.0.breeze5.23.80/kdecoration/breezedecoration.cpp:1360:17: error: ‘setBlurRegion’ was not declared in this scope
 1360 |                 setBlurRegion( QRegion( m_windowPath->toFillPolygon().toPolygon()) ) ;
      |                 ^~~~~~~~~~~~~
/home/ehsant/.cache/yay/classik/src/classik-3.0.breeze5.23.80/kdecoration/breezedecoration.cpp:1361:20: error: ‘setBlurRegion’ was not declared in this scope
 1361 |             } else setBlurRegion( QRegion() );
      |                    ^~~~~~~~~~~~~
make[2]: *** [kdecoration/CMakeFiles/classikdecoration.dir/build.make:131: kdecoration/CMakeFiles/classikdecoration.dir/breezedecoration.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:512: kdecoration/CMakeFiles/classikdecoration.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
`

**Comment by paulmcauley** [comment] 2022-06-11 13:10
> Hi, I have same problem. In AUR. Erorr = `home/ehsant/.cache/yay/classik/src/classik-3.0.breeze5.23.80/kdecoration/breezedecoration.cpp: In member function ‘void Breeze::Decoration::updateBlur()’: /home/ehsant/.cache/yay/classik/src/classik-3.0.breeze5.23.80/kdecoration/breezedecoration.cpp:1355:13: error: ‘setBlurRegion’ was not declared in this scope 1355 | setBlurRegion( QRegion() ); | ^~~~~~~~~~~~~ /home/ehsant/.cache/yay/classik/src/classik-3.0.breeze5.23.80/kdecoration/breezedecoration.cpp:1360:17: error: ‘setBlurRegion’ was not declared in this scope 1360 | setBlurRegion( QRegion( m_windowPath->toFillPolygon().toPolygon()) ) ; | ^~~~~~~~~~~~~ /home/ehsant/.cache/yay/classik/src/classik-3.0.breeze5.23.80/kdecoration/breezedecoration.cpp:1361:20: error: ‘setBlurRegion’ was not declared in this scope 1361 | } else setBlurRegion( QRegion() ); | ^~~~~~~~~~~~~ make[2]: *** [kdecoration/CMakeFiles/classikdecoration.dir/build.make:131: kdecoration/CMakeFiles/classikdecoration.dir/breezedecoration.cpp.o] Error 1 make[1]: *** [CMakeFiles/Makefile2:512: kdecoration/CMakeFiles/classikdecoration.dir/all] Error 2 make: *** [Makefile:136: all] Error 2 ==> ERROR: A failure occurred in build(). Aborting... `

This is a duplicate of #23 The current builds from master require Plasma 5.25 which will be released next week. Plasma 5.25 includes the needed setBlurRegion function.

**Closed** 2022-06-20 00:53 UTC
Labels: duplicate
