### ISSUE TITLE
ERROR: A failure occurred in build() on Arch Linux (classik-3.0.breeze5.23.80)

### ISSUE THREAD

**Issue by MountainX** [paulmcauley/classik#29] opened 2022-05-31 19:52 UTC
This error was reported twice at:
https://aur.archlinux.org/packages/classik#comment-865832

```
/home/lee/Code/AUR/classik/src/classik-3.0.breeze5.23.80/kstyle/breezestyle.cpp:7650:17: note: here
 7650 |                 default:
      |                 ^~~~~~~
make[2]: *** [kstyle/CMakeFiles/classik.dir/build.make:589: kstyle/CMakeFiles/classik.dir/breezestyle.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:617: kstyle/CMakeFiles/classik.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```
I am also getting the same error. Instead of reporting there, I am opening this issue. 

I am not using any AUR helpers. I am using:

    git clone https://aur.archlinux.org/classik.git
    cd classik
    makepkg -s

**Comment by paulmcauley** [comment] 2022-05-31 20:04
This is a duplicate of #27 . It is caused by a GCC update in your distribution, and a fix has already been made on master here. I will also make a new release in the next month or so.

**Closed** 2022-05-31 20:04 UTC
Labels: duplicate

**Comment by MountainX** [comment] 2022-07-17 21:55
> I will also make a new release in the next month or so.

Hi. Thanks again for your work on Classik. Can you recommend an AUR package to use? Is either of these currently working on Arch?

- [classik 3.0.breeze5.23.80-1](https://aur.archlinux.org/packages/classik)

- [classik-git 3.0.breeze5.23.80.r60.g880bf320-1](https://aur.archlinux.org/packages/classik-git)

I'm pretty sure the first one is still not building, but the 2nd package pulls from the master branch.
